# 应用端口
server:
  port: 8004
spring:
  application:
    # 应用名称
    name: j-cloud-consumer

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka

logging:
  level:
    root: INFO

