server:
  port: 8007
spring:
  application:
    name: j-cloud-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
zuul:
  ignoredServices: '*'
  routes:
    app-a:
      path: /u/**
      serviceId: provider-user

