spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://10.0.40.233:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: janezhou
    password: 123456
    host: 10.0.40.233
    port: 15672
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 10.0.40.233
    database: 0
    port: 6379
  cache:
    cache-names: menus_cache
server:
  port: 9001
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/



